import StyleDictionary from 'style-dictionary';

/**
 * Custom formatter for TypeScript tokens with full type safety
 */
const typescriptFormatter = ({ dictionary }) => {
  // Recursively build the tokens object
  const buildTokens = (obj, path = []) => {
    const result = {};
    for (const [key, value] of Object.entries(obj)) {
      if (value.$value !== undefined) {
        // Leaf node - has a $value
        result[key] = value.$value;
      } else {
        // Nested object
        result[key] = buildTokens(value, [...path, key]);
      }
    }
    return result;
  };

  const tokenData = buildTokens(dictionary.tokens);

  return `/**
 * Design Tokens
 * Auto-generated by Style Dictionary - DO NOT EDIT
 * 
 * This file provides type-safe access to all design tokens
 * defined in the Isolate UI design system.
 */

export const tokens = ${JSON.stringify(tokenData, null, 2)} as const;

export type Tokens = typeof tokens;

export default tokens;
`;
};

/**
 * Style Dictionary v4 Configuration
 * Transforms design tokens from DTCG format to CSS variables and TypeScript
 */
export default {
  // Source token files
  source: ['libs/shared/tokens/src/tokens.json'],

  // Output platforms
  platforms: {
    // CSS Variables output
    css: {
      // Use built-in DTCG transformers
      transformGroup: 'css',

      // Add custom prefix to all CSS variables
      prefix: 'isolate',

      // Output configuration
      buildPath: 'libs/shared/tokens/gen/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },

    // TypeScript output
    ts: {
      transformGroup: 'js',

      buildPath: 'libs/shared/tokens/gen/ts/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'typescript/tokens',
        },
      ],
    },
  },
};

// Register the custom TypeScript formatter
StyleDictionary.registerFormat({
  name: 'typescript/tokens',
  format: typescriptFormatter,
});
